### PR TITLE
Add wf-shell components (+docks category)

### PR DESCRIPTION
**Pull request by solarkraft**

### CODE REVIEW

**Comment by natpen** [comment]
Thanks! Do you know for sure if these components work independent of wayfire? E.g., if you're using Sway as your WM

**Comment by solarkraft** [comment]
Good call. I tested them a bit in sway. 

wf-background just works. 
wf-dock exits with the message `Compositor doesn't support wlr-foreign-toplevel-management, exiting.`
wf-panel starts and is positioned correctly, but the application menu seems to have focus issues while entering text. 

To me these problems seem to be sway-specific and not because the programs are wayfire-specific.

**Comment by natpen** [comment]
I think you may have added some commits that weren't intended :) (looks like some are part of the start of a new `awesome-` repo)

**Comment by solarkraft** [comment]
Sorry, forgot that it would affect the PR!

**Pull request closed without merging**
