### PR TITLE
Yet another suggestion -- CopyQ

### PR DESCRIPTION
**Pull request by DN-debug**
Hi Nat,

This time, it is a clipboard manager called CopyQ. This works via XWayland though, which is why I am not sure whether this qualifies to be in the list of pure Wayland software or not, but that is for you to decide. 

Many thanks
DN-debug

### CODE REVIEW

**Comment by snvmk** [comment]
why would it be pure wayland when it cant run in pure wayland environment?

**Comment by DN-debug** [comment]
I believe you might want to re-read my statement and the one you wrote as well, I never said it to be pure Wayland.

**Comment by xPMo** [comment]
The GUI is X11, but it talks to the clipboard over Wayland: https://github.com/hluk/CopyQ/tree/master/src/platform/x11/systemclipboard

**Comment by DN-debug** [comment]
xPMo is correct, XWayland always works as a proxy in-between, so it is natural for it to intercept and forward requests to and from Wayland.

@natpen It doesn't appear to me that the XWayland applications are going to be part of this list, so what do you think? Shall I close it? Please suggest.

**Comment by xPMo** [comment]
imo it should be added, it has a native clipboard implementation (just like the `wl-clipboard` tools).

**Pull request merged**
