### PR TITLE
add tym terminal emulator

### PR DESCRIPTION
**Pull request by mhdzli**

### CODE REVIEW

**Comment by apiraino** [comment]
I think it's this [github project](https://github.com/endaaman/tym), correct?

**Comment by mhdzli** [comment]
@apiraino 
Yes that's it.

**Comment by mhdzli** [comment]
@apiraino 
Isn't that what I linked?

**Comment by apiraino** [comment]
> @apiraino Isn't that what I linked?

my apologies, of course it is :)

**Comment by natpen** [comment]
Is there anything about this that's wayland-specific? I grepped the project files for `wayland` and `wlroots` and didn't see anything. If there's nothing about it that's wayland-specific, I feel it may not be suited for addition to this list (even if it's a great project for other reasons :smile: ).

**Pull request closed without merging**
